name: comment issue on failing
on:
  workflow_run:
    workflows: ["this close to me"]
    types: [completed]
jobs:      
  on_failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: printf '%c, your run failed' "<0001f97a>"
      #- run: echo "\xf0\x9f\xa5\xba your run failed" 
