name: comment issue on failing
on:
  workflow_run:
    workflows: ["this close to me"]
    types: [completed]
jobs:      
  on_failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo "\x1F979, your run failed" 
